### ISSUE TITLE
Add configuration option to disable modules at runtime

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-docs#209]
It should be configurable which modules are used to sample data on the device to send location data to the cloud **at runtime** so the performance of this data can be compared.

See https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/issues/460

---

Introduce a generic way to disable sampling of data from specific modules at runtime:

```json
{
  "cfg": {
    "nod": [
      "gnss",
      "ncell"
    ]
  }
}
```

This disables sampling of data ("**no** **d**ata") of the GNSS module.

**Comment by simensrostad** [comment]
Added a separate entry for neighbor cell data.

**Comment by simensrostad** [comment]
We should start off with these two
