### ISSUE TITLE
Unknown board nrf9160_pca10090ns

### ISSUE THREAD

**Issue by b2infosoft-manoj** [NordicSemiconductor/asset-tracker-cloud-docs#416]
I am trying to build the project from my local machine but when I run this west build -p always -b nrf9160_pca10090ns -- -DOVERLAY_CONFIG="overlay-aws.conf;overlay-debug.conf;asset-tracker-cloud-firmware-azure.conf;firmware.conf"
then got below error, I have already connected correct board with my machine but not sure why getting below error.

CMake Error at /Users/flutter/nrf-asset-tracker/azure/ncs/zephyr/cmake/app/boilerplate.cmake:389 (message):
  Invalid BOARD; see above.
Call Stack (most recent call first):
  /Users/flutter/nrf-asset-tracker/azure/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /Users/flutter/nrf-asset-tracker/azure/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:9 (find_package)

**Comment by coderbyheart** [comment]
Thank you for reporting this issue, the board names were changed in 1.7.0 and we missed this change. It's now corrected in d4cb22dc984d2a77177d05390112f21a84115494.

Please use `nrf9160dk_nrf9160_ns` as the board identifier.
