### ISSUE TITLE
Getting error on Building the project using your local system

### ISSUE THREAD

**Issue by b2infosoft-manoj** [NordicSemiconductor/asset-tracker-cloud-docs#421]
Hi,
I am following all instructions but this command sudo pip3 install -r mcuboot/scripts/requirements.txt giving error "Could not open requirement file: No such file or directory 'mcuboot/scripts/requirements.txt'", I am sure I followed all of previous command properly.
Could you please guide what I am missing?

**Comment by coderbyheart** [comment]
Hei, not sure about that. It seems that we got a bit out of sync with the manual build instructions.
Looking at the Docker image, this seems to be neccessary steps:
https://github.com/coderbyheart/fw-nrfconnect-nrf-docker/blob/saga/Dockerfile#L72-L79

```bash
sudo pip3 install -r bootloader/mcuboot/scripts/requirements.txt
```

Let me know if that fixes it.
