### ISSUE TITLE
Adapt new Nordic docs layout style

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-docs#465]
A new layout has been introduced to [developer.nordicsemi.com](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/asset_tracker_v2/README.html), and the nRF Asset Tracker docs need to follow this.

Theme source: https://github.com/nrfconnect/doc-sphinx-ncs-theme

![Image](https://user-images.githubusercontent.com/188915/170038132-7e2095ea-ca8c-4724-9dbb-7581c262ac40.png)

- [ ] contact @umapraseeda and Richa Pandey before beginning to work on this

**Comment by peknis** [comment]
Have you talked about this with @umapraseeda or Richa Pandey? Both have been active participant in planning of the new layout.

**Comment by coderbyheart** [comment]
No, because we have not started to work on this.

**Comment by peknis** [comment]
Okay. Now you know who to contact first.
