### ISSUE TITLE
Add support for WiFi site surveys

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-docs#605]
See https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/discussions/590

**Comment by coderbyheart** [comment]
Please create a PR for this

**Comment by coderbyheart** [comment]
Also JSON format needs to be documented.

**Comment by pudkrong** [comment]
Shall we put the link to nRF Cloud API instead? Otherwise, we need to keep update our documents every time nRF Cloud API is changed.

**Comment by coderbyheart** [comment]
No we need to document the JSON that device sends to nRF Asset Tracker.

**Comment by pudkrong** [comment]
Now, I got what you mean. Working on it now.
