### ISSUE TITLE
fix: confusing sentence

### ISSUE THREAD

**Issue by MLopezJ** [NordicSemiconductor/asset-tracker-cloud-docs#875]
In `Install the nRF Asset Tracker into your Azure account`, step number 17 is confusing with its explanation: 

https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/blob/0108cfaaa8ede17524a4a1a369e485f043422607/docs/azure/GettingStarted/Deploy.rst?plain=1#L122

I suggest changing it to:

`Save your nRF Cloud team ID to the environment variable...`

**Comment by coderbyheart** [comment]
Commit message should have been `fix: ...` so that the docs are actually release with a new version.
